name: music_player
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_native_splash: ^2.2.9
  firebase_core: ^1.20.0
  firebase_auth: ^3.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

  build_runner: ^2.3.3
  bdd_widget_test: ^1.2.1
  flutter_driver:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
  #  - assets/
   - assets/images/logo.png
  
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_native_splash:
    android: true
    ios: true
    web: false
    image: "assets/images/logo.png"
